import Head from "next/head";
import Link from "next/link";
import LearnMore from "@/components/LearnMore";
import Splash from "@/components/Splash";
import splash from "../assets/splash-women.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Alexandria:wght@400;700&family=Inter:wght@400;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <main className="flex min-h-screen flex-col">
        {/* Splash */}
        <Splash />

        {/* Nurses United For All */}
        <section className="flex flex-col gap-2 p-12 sm:p-20 bg-white text-primary">
          <h2 className="text-2xl sm:text-4xl font-bold">NURSES UNITED FOR ALL</h2>
          <p className="tracking-wide">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget tincidunt sapien. Donec faucibus lectus eget ex dictum, sit amet venenatis mauris hendrerit. Ut vitae diam velit. Integer arcu arcu, malesuada eget sem in, pellentesque dapibus libero. Nunc dictum lectus purus, id gravida nisi gravida vulputate.
          </p>

          <div className="flex flex-row-reverse">
            <LearnMore link={"/nurses"} />
          </div>
        </section>

        {/* Wins */}
        <section className="flex flex-row flex-wrap gap-16 p-12 sm:p-20 bg-primary text-white">
          <div className="flex-1 flex flex-col gap-3 items-start">
            <h2 className="text-4xl font-bold">WINS</h2>
            <p className="tracking-wide">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget tincidunt sapien. Donec faucibus lectus eget ex dictum, sit amet venenatis mauris hendrerit. Ut vitae diam velit. Integer arcu arcu, malesuada eget sem in, pellentesque dapibus libero. Nunc dictum lectus purus, id gravida nisi gravida vulputate.
            </p>
            <LearnMore link={"/wins"} />
          </div>

          <div className="flex flex-wrap sm:flex-row gap-10">
            <img src={splash.src} width={300} height={400} className="object-contain" />
            <img src={splash.src} width={300} height={400} className="object-cover" />
          </div>

        </section>

        {/* Vision */}
        <section className="flex flex-col flex-wrap sm:flex-row  gap-2 p-12 sm:p-20 bg-white text-primary">
          <div className="flex items-center justify-center">
            <h2 className="text-4xl font-bold pb-3 mb:pb-0">VISION</h2>
          </div>

          <div className="flex flex-col sm:flex-row flex-grow gap-8 items-center justify-center text-white">
            <div className="justify-start items-start flex flex-col gap-2 bg-primary w-[340px] h-auto rounded-sm p-8">
              <h3 className="text-2xl font-bold">MISSION 1</h3>
              <p className="tracking-wide font-normal">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget tincidunt sapien. Donec faucibus lectus eget ex dictum, sit amet venenatis mauris hendrerit. Ut vitae diam velit. Integer arcu arcu, malesuada eget sem in, pellentesque dapibus libero. Nunc dictum lectus purus, id gravida nisi gravida vulputate.
              </p>
              <LearnMore link={"/vision/{mission_1}"} />
            </div>

            <div className="justify-start items-start flex flex-col gap-2 bg-primary w-[340px] h-auto rounded-sm p-8">
              <h3 className="text-2xl font-bold">MISSION 2</h3>
              <p className="tracking-wide font-normal">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget tincidunt sapien. Donec faucibus lectus eget ex dictum, sit amet venenatis mauris hendrerit. Ut vitae diam velit. Integer arcu arcu, malesuada eget sem in, pellentesque dapibus libero. Nunc dictum lectus purus, id gravida nisi gravida vulputate.
              </p>
              <LearnMore link={"/vision/{mission_2}"} />
            </div>

            <div className="justify-start items-start flex flex-col gap-2 bg-primary w-[340px] h-auto rounded-sm p-8">
              <h3 className="text-2xl font-bold">MISSION 3</h3>
              <p className="tracking-wide font-normal">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget tincidunt sapien. Donec faucibus lectus eget ex dictum, sit amet venenatis mauris hendrerit. Ut vitae diam velit. Integer arcu arcu, malesuada eget sem in, pellentesque dapibus libero. Nunc dictum lectus purus, id gravida nisi gravida vulputate.
              </p>
              <LearnMore link={"/vision/{mission_3}"} />
            </div>
        </div>

        </section>

        {/* Sign up for Updates */}
        <section className="flex flex-col gap-5 sm:p-20 items-center justify-center p-10 bg-primary text-white">
          <h2 className="text-4xl font-bold">SIGN UP FOR UPDATES</h2>
          <form className="flex flex-col gap-4">
            <input className="h-10 rounded-sm w-76 p-6 text-primary" placeholder="Name" />
            <input className="h-10 rounded-sm w-76 p-6 text-primary" placeholder="Phone Number" />
            <button className="h-10 rounded-sm w-76 p-6 text-white bg-secondary font-bold">
              JOIN
            </button>
          </form>
        </section>

        {/* Footer */}
        <section className="flex p-20 bg-white">


        </section>
      </main>
    </>
  );
}
